###
GET  http://localhost:4000/api/ventas/get-ventas-by-date
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

###
GET  http://localhost:4000/api/ventas/get-ingreso-total
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

###
GET  http://localhost:4000/api/ventas/get-waiter-ventas
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

###
GET  http://localhost:4000/api/ventas/get-ranked-waiters
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

###
GET  http://localhost:4000/api/ventas/get-cashier-ventas
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

###
GET  http://localhost:4000/api/ventas/get-prod-rentables
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

###
GET  http://localhost:4000/api/ventas/get-cat-rentables
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

###
GET  http://localhost:4000/api/ventas/get-prod-mas-vendidos
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

###
GET  http://localhost:4000/api/ventas/get-ranked-metodos
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

###
GET  http://localhost:4000/api/ventas/get-ventas-by-zone
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

###
GET  http://localhost:4000/api/ventas/get-ingresos-per-day
content-type: application/json

{
    "inicio":"2019-01-01 14:00:00",
    "fin": "2019-01-01 14:06:00"
}

# GET http://localhost:4000/api/ventas/
# content-type: application/json

# {
#     "inicio":"2019-01-01 14:00:00",
#     "fin": "2019-01-01 15:00:00",
#     "name": "Roberto Ortega"
# }

# POST  http://localhost:4000/api/ventas

# content-type: application/json

# {
#     "inicio":"2019-04-01",
#     "fin": "2019-04-30T00:00:00"
# }